[package]
edition.workspace = true
name = "backend"
version.workspace = true

[dependencies]
axum = "0.8.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.46.1", features = ["full"]}
tokio-tungstenite = "0.27.0"
ulid = "1.2.1"
